// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADARoI7jwYuFHFkaGYNJvHDiimdPXn0oY',
    appId: '1:1086855213708:web:0970d6f090695564e2c1a9',
    messagingSenderId: '1086855213708',
    projectId: 'safeher-95681',
    authDomain: 'safeher-95681.firebaseapp.com',
    storageBucket: 'safeher-95681.firebasestorage.app',
    measurementId: 'G-W9X8WVWT4T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB03FMOCuDabNUp58nw8YCY3F-VqHdBZPg',
    appId: '1:1086855213708:android:42f6f475ed995d0be2c1a9',
    messagingSenderId: '1086855213708',
    projectId: 'safeher-95681',
    storageBucket: 'safeher-95681.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQnaeGg8HgwqwxAdBa6BfMmvhYVtOqK-8',
    appId: '1:1086855213708:ios:0e6bcc1cc6c930c7e2c1a9',
    messagingSenderId: '1086855213708',
    projectId: 'safeher-95681',
    storageBucket: 'safeher-95681.firebasestorage.app',
    iosClientId: '1086855213708-8g2ihf3s3j0uc5k58douqgacelg1btlr.apps.googleusercontent.com',
    iosBundleId: 'com.example.sheguard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQnaeGg8HgwqwxAdBa6BfMmvhYVtOqK-8',
    appId: '1:1086855213708:ios:0e6bcc1cc6c930c7e2c1a9',
    messagingSenderId: '1086855213708',
    projectId: 'safeher-95681',
    storageBucket: 'safeher-95681.firebasestorage.app',
    iosClientId: '1086855213708-8g2ihf3s3j0uc5k58douqgacelg1btlr.apps.googleusercontent.com',
    iosBundleId: 'com.example.sheguard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyADARoI7jwYuFHFkaGYNJvHDiimdPXn0oY',
    appId: '1:1086855213708:web:911dc5e6924394cde2c1a9',
    messagingSenderId: '1086855213708',
    projectId: 'safeher-95681',
    authDomain: 'safeher-95681.firebaseapp.com',
    storageBucket: 'safeher-95681.firebasestorage.app',
    measurementId: 'G-S6YPLL59Y4',
  );
}
